apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::861088354544:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-P9I5J71MWATA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::861088354544:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-18T06:59:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1566"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 1851b566-0db3-4dcd-adcc-57062ee7c9cc
